import { ElementRef } from '@angular/core';
import { BooleanInputAccept } from 'novo-elements/utils';
import { TypographyLength, TypographySize, TypographyWeight } from '../text.types';
import * as i0 from "@angular/core";
export declare class NovoBaseTextElement {
    protected element: ElementRef;
    size: TypographySize;
    weight: TypographyWeight;
    lineLength: TypographyLength;
    color: string;
    get hb_classBinding(): string;
    disabled: boolean;
    static readonly ngAcceptInputType_disabled: BooleanInputAccept;
    muted: boolean;
    static readonly ngAcceptInputType_muted: BooleanInputAccept;
    error: boolean;
    static readonly ngAcceptInputType_error: BooleanInputAccept;
    marginBefore: boolean;
    static readonly ngAcceptInputType_marginBefore: BooleanInputAccept;
    marginAfter: boolean;
    static readonly ngAcceptInputType_marginAfter: BooleanInputAccept;
    capitialize: boolean;
    static readonly ngAcceptInputType_capitalize: BooleanInputAccept;
    uppercase: boolean;
    static readonly ngAcceptInputType_uppercase: BooleanInputAccept;
    nowrap: boolean;
    static readonly ngAcceptInputType_nowrap: BooleanInputAccept;
    ellipsis: boolean;
    static readonly ngAcceptInputType_ellipsis: BooleanInputAccept;
    smaller: boolean;
    static readonly ngAcceptInputType_smaller: BooleanInputAccept;
    larger: boolean;
    static readonly ngAcceptInputType_larger: BooleanInputAccept;
    thin: boolean;
    static readonly ngAcceptInputType_thin: BooleanInputAccept;
    lighter: boolean;
    static readonly ngAcceptInputType_lighter: BooleanInputAccept;
    light: boolean;
    static readonly ngAcceptInputType_light: BooleanInputAccept;
    medium: boolean;
    static readonly ngAcceptInputType_medium: BooleanInputAccept;
    bold: boolean;
    static readonly ngAcceptInputType_bold: BooleanInputAccept;
    bolder: boolean;
    static readonly ngAcceptInputType_bolder: BooleanInputAccept;
    extrabold: boolean;
    static readonly ngAcceptInputType_extrabold: BooleanInputAccept;
    constructor(element: ElementRef);
    get nativeElement(): any;
    static ɵfac: i0.ɵɵFactoryDeclaration<NovoBaseTextElement, never>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<NovoBaseTextElement, never, never, { "size": "size"; "weight": "weight"; "lineLength": "lineLength"; "color": "color"; "disabled": "disabled"; "muted": "muted"; "error": "error"; "marginBefore": "marginBefore"; "marginAfter": "marginAfter"; "capitialize": "capitialize"; "uppercase": "uppercase"; "nowrap": "nowrap"; "ellipsis": "ellipsis"; "smaller": "smaller"; "larger": "larger"; "thin": "thin"; "lighter": "lighter"; "light": "light"; "medium": "medium"; "bold": "bold"; "bolder": "bolder"; "extrabold": "extrabold"; }, {}, never>;
}
